server:
  port: 8081

spring:
  application:
    name: lms-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: lms
    password: sarasu10
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  security:
    user:
      name: sanketh
      password: sanketh

